maxflow
tigergraph/gsql-graph-algorithms pull request #59
Opened 2021-10-04 13:59 UTC by tommytgraph

2021-10-04 18:50 UTC, Boyu1997 requested changes
Hi Tommy,
Great job implementing the MaxFlow algorithms! Some minor changes before the merge.

2021-10-04 18:50 UTC, Boyu1997 commented on algorithms/Path/maxflow/tg_maxflow.gsql
> +       STRING file_path = "/home/tigergraph/tg_query_output.csv"){
set default file_path as `STRING file_path = ""`
this aligns better with other algorithms in the library

2021-10-04 18:50 UTC, Boyu1997 commented on algorithms/Path/maxflow/tg_maxflow.gsql
> +	END;
think this type checking plus the CASE statement is a good way to make `e.getAttr(ATTRIBUTE_NAME, TYPE_STRING)` take different attributes type input; given TYPE_STRING still only takes a static string in 3.2
should consider adopting a similar approach for future algorithms in the library @victor-gsl

2021-10-04 18:50 UTC, Boyu1997 commented on algorithms/Path/maxflow/tg_maxflow.gsql
> +  @@cap_threshold = pow(3, float_to_int(log(@@cap_threshold)/log(3)));
add some comments on how cap_threshold is calculated/ used?
a reference to the capacity scaling algorithm will be helpful
you can do it as general information comments at the beginning or when the cap_threshold is used

2021-10-04 18:50 UTC, Boyu1997 commented on algorithms/Path/maxflow/tg_maxflow.gsql
> +	END;
please add an empty line before `##### Output #####` and fix the indentation

2021-10-04 18:50 UTC, Boyu1997 commented on algorithms/Path/maxflow/tg_maxflow.gsql
> +       BOOL print_accum = TRUE, BOOL display_edges = TRUE, BOOL spit_to_file = FALSE,
parameter `spit_to_file` was never used in the query
please remove it if not needed

2021-10-04 18:50 UTC, Boyu1997 commented on algorithms/Path/maxflow/tg_maxflow.gsql
> +   e_type: edge types to traverse                   display_edges: output edges for visualization
comment for `display_edges` should clarify this only works when `print_accum = TRUE`

2021-10-05 00:32 UTC, wyatt-joyner-tg approved these changes
I see that you got all the style changes in! Great work, Tommy.

2021-10-05 00:35 UTC, merged

2021-10-05 00:38 UTC, Boyu1997 commented
@tommytgraph @wyatt-joyner-tg :rocket::rocket::rocket: